#!/usr/bin/bash

if [ ! -d "build/lsddonation" ]
then
  mkdir build/lsddonation
else
  rm -rf build/lsddonation
  mkdir build/lsddonation
fi

cp -r dummy build/lsddonation/dummy 

cd build

zip -r lsddonation.zip lsddonation/*





