name: Generate Installable Plugin, and Upload to RealeaseAPI
on:
  release:
    types: [published]
jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build project
        run: |
          echo "completed"
