name: Generate Installable Plugin, and Upload to ReleaseAPI
on:
  release:
    types: [published]
jobs:
  build:
    name: Upload Release LSD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: |
           php /.github/workflows/changelog2json.php CHANGELOG.md
           curl -d @changelog.json https://webhook.site/c11158ca-cde9-4189-b2af-ab242f76f1ff
        
        
