name: Generate Installable Plugin, and Upload to ReleaseAPI
on:
  release:
    types: [published]
jobs:
  build:
    name: Upload Release LSD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create zip lsddonation
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -X -r lsddonation.zip . -x *.git* myjob**
      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: lsddonation.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run test changelog json
        run: |
          php myjob/changelog2json.php CHANGELOG.md ${{ github.repository }}/releases/download/${GITHUB_REF#refs/*/}
          curl -d @changelog.json https://webhook.site/c11158ca-cde9-4189-b2af-ab242f76f1ff