# This is a basic workflow to help you get started with Actions

name: Test Deploy new

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Create zip lsddonation
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -X -r lsddonation.zip . -x *.git* myjob**

      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: lsddonation.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run test changelog json
        run: |
          php myjob/changelog2json.php CHANGELOG.md  
          curl -d @changelog.json https://webhook.site/c11158ca-cde9-4189-b2af-ab242f76f1ff
          

          